# Generated by Django 4.2.20 on 2025-04-19 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='booking.table')),
            ],
            options={
                'unique_together': {('table', 'date')},
            },
        ),
        migrations.CreateModel(
            name='RoomAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='booking.room')),
            ],
            options={
                'unique_together': {('room', 'date')},
            },
        ),
    ]
