# Generated by Django 4.2.20 on 2025-04-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_room_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='latitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='longitude',
            field=models.FloatField(default=100.0),
            preserve_default=False,
        ),
    ]
