# Generated by Django 4.2.20 on 2025-04-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_hotel_latitude_hotel_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
