# Generated by Django 4.2.20 on 2025-04-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_hotel_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Bomzh', 'bomzh'), ('Econom', 'Econom'), ('Comfort', 'Comfort'), ('Luxury', 'Luxury')], default='Econom', max_length=100),
        ),
    ]
