# Generated by Django 4.2.20 on 2025-04-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_room_photo_url_alter_room_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='amenities_json',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
