# Generated by Django 4.2.20 on 2025-04-22 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_amenity_hotel_amenities'),
        ('booking', '0006_hotel_amenities_json'),
    ]

    operations = [
    ]
